name: Hello world workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: hello world
        run: echo "Hellow World"
        shell: bash
  
  goodbye:
    runs-on: ubuntu-latest
    steps:
      - name: googdby world
        run: echo "Goodbye world"
        shell: bash